// helper methods for initializeUser.

import AsyncStorage from "@react-native-async-storage/async-storage";

const USER_ID_KEY = "storedFirebaseUid";

// saves the uid generated by firebase to local storage
export const saveUid = async (uid: string) => {
  await AsyncStorage.setItem(USER_ID_KEY, uid);
};

// retrieves the uid generated by firebase to local storage
// returns null if no uid is found
export const getStoredUid = async (): Promise<string | null> => {
  return await AsyncStorage.getItem(USER_ID_KEY);
};
